### ISSUE TITLE
Feature Suggestion: Window Width Display & Considering Multiple Panes

### ISSUE THREAD

**Issue by chrisgrieser** [mybuddymichael/obsidian-hide-sidebars-when-narrow#1]
Hi, first of all thanks for this plugin! I use it together with Window Manager [Moom](https://apps.apple.com/us/app/moom/id419330170?mt=12) and it is incredibly useful when automatically re-arranging windows with it.

One thing that would make it easier to set up is simply to display the current window width in the settings menu. It took me a bit to figure out what the exact width of my current window is, and I want to configure each sidebar. 

Another thing that would be practical is to consider the number of panes. If I only have one pane, I'd like to have both sidebars, but when I have two panes, I would like to hide the sidebars, so each pane has enough space. Currently, this plugin only considers window width, not pane width.

**Comment by mybuddymichael** [comment]
I'm so glad you find this plugin useful. I also use a window manager and appreciate that the window adapts when I need it to.

As far as those feature requests though, I like them! Unfortunately I won't have any time in the near future to work on them. But I'll happily consider any pull requests that come along.

**Comment by NomarCub** [comment]
Hi!
I took over this plugin in a fork that you can find [here](https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize). Installed Obsidian plugins should auto-update to it automatically. The first release is basically the same, with the #5 proposal added that addresses #2.

If this issue is still relevant to you, please submit it there too.

**Comment by NomarCub** [comment]
My bad, issues weren't open on my repo for some reason. They are now.
